#!/usr/bin/env bash

docker run --detach --rm \
  --user root \
  --name="xubuntu-vm" \
  --hostname="$(hostname)" \
  --publish="3392:3389/tcp" \
  --shm-size="2g" \
  --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
  --mount type=bind,source=/Users/dishin/shared,target=/shared \
  xubuntu-dev:latest /bin/bash
